name: link_text
description: Easy to use text widget for Flutter apps, which converts inlined URLs into clickable links. Allows custom styling.
version: 0.2.1
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/link_text

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: